stages:
  - build
  - docs

variables:
  V: "0"
  MAKEFLAGS: "-j8 --no-keep-going"
  GIT_SUBMODULE_STRATEGY: recursive

.apply_sdk_patches: &apply_sdk_patches
  - echo "Applying SDK patches to WebRTC SDK submodule..."
  - cd $CI_PROJECT_DIR/amazon-kinesis-video-streams-webrtc-sdk-c
  - git am $CI_PROJECT_DIR/patches/*.patch
  - cd $CI_PROJECT_DIR

.build_examples: &build_examples
  - apt-get update && apt-get install -y pkg-config
  - *apply_sdk_patches
  - for TARGET in $TARGETS; do
  - for EXAMPLE in $EXAMPLES; do
  - if [ $EXAMPLE == "network_adapter" ] && [ $TARGET != "esp32c6" ] && [ $TARGET != "esp32c5" ]; then
  - echo "Skipping $EXAMPLE for $TARGET (network_adapter only for esp32c6/esp32c5)"
  - continue
  - fi
  - if [ $EXAMPLE == "signaling_only" ] && [ $TARGET == "esp32p4" ]; then
  - echo "Skipping $EXAMPLE for $TARGET (not supported)"
  - continue
  - fi
  - example_path=$CI_PROJECT_DIR/examples/$EXAMPLE
  - cd $example_path
  - echo "Building $EXAMPLE for $TARGET"
  - idf.py set-target $TARGET
  - idf.py build
  - mkdir -p $CI_PROJECT_DIR/build_output/$EXAMPLE/$TARGET/
  - cp $example_path/build/*.bin $CI_PROJECT_DIR/build_output/$EXAMPLE/$TARGET/
  - cp $example_path/build/*.elf $CI_PROJECT_DIR/build_output/$EXAMPLE/$TARGET/
  - cp $example_path/build/*.map $CI_PROJECT_DIR/build_output/$EXAMPLE/$TARGET/
  - rm -rf build sdkconfig
  - done
  - done
  - cd $CI_PROJECT_DIR

.build_template:
  stage: build
  tags:
    - build
  artifacts:
    paths:
      - build_output/
    expire_in: 6 mos
  script:
    - *build_examples

build_idf_v5.4:
  extends: .build_template
  image: espressif/idf:release-v5.4
  variables:
    EXAMPLES: webrtc_classic esp_camera signaling_only streaming_only network_adapter
    TARGETS: esp32 esp32s3 esp32c6 esp32p4

build_idf_v5.5:
  extends: .build_template
  image: espressif/idf:release-v5.5
  variables:
    EXAMPLES: webrtc_classic esp_camera signaling_only streaming_only network_adapter
    TARGETS: esp32 esp32s3 esp32c6 esp32c5 esp32p4

build_docs:
  stage: docs
  image: python:3.11
  tags:
    - build
  artifacts:
    paths:
      - docs/_build/
    expire_in: 6 mos
  script:
    - pip install -r docs/requirements.txt
    - cd docs
    - build-docs -l en -t esp32
