#pragma once

#include "sdkconfig.h"

#if !CONFIG_BSP_SELECT_NONE
#if CONFIG_ESP32_P4_FUNCTION_EV_BOARD
#include "boards/esp32-p4-function-ev-board-v1.4/example_video_common_board.h"
#elif CONFIG_BSP_SELECT_ESP32_S3_EYE
#include "boards/esp32-s3-eye/example_video_common_board.h"
#elif CONFIG_BSP_SELECT_ESP32_P4_EYE
#include "boards/esp32-p4-eye/example_video_common_board.h"
#else
#error Add config to boards directory
#endif
#else
#include "boards/customized/example_video_common_board.h"
#endif

#if CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP
#define EXAMPLE_SCCB_I2C_PORT_INIT_BY_APP              CONFIG_EXAMPLE_SCCB_I2C_PORT_INIT_BY_APP
#endif /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */

/**
 * @brief MIPI-CSI camera sensor common configuration
 */
#if CONFIG_EXAMPLE_ENABLE_MIPI_CSI_CAM_SENSOR
#define EXAMPLE_ENABLE_MIPI_CSI_CAM_SENSOR              1
#if CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP
#define EXAMPLE_MIPI_CSI_SCCB_I2C_PORT                  EXAMPLE_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */
#define EXAMPLE_MIPI_CSI_SCCB_I2C_PORT                  CONFIG_EXAMPLE_MIPI_CSI_SCCB_I2C_PORT
#endif /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */

#define EXAMPLE_MIPI_CSI_SCCB_I2C_FREQ                  CONFIG_EXAMPLE_MIPI_CSI_SCCB_I2C_FREQ

#if CONFIG_EXAMPLE_ENABLE_MIPI_CSI_CAM_MOTOR
#define EXAMPLE_ENABLE_MIPI_CSI_CAM_MOTOR              1
#if CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP
#define EXAMPLE_MIPI_CSI_CAM_MOTOR_SCCB_I2C_PORT       EXAMPLE_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */
#define EXAMPLE_MIPI_CSI_CAM_MOTOR_SCCB_I2C_PORT       CONFIG_EXAMPLE_MIPI_CSI_CAM_MOTOR_SCCB_I2C_PORT
#endif /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */

#define EXAMPLE_MIPI_CSI_CAM_MOTOR_SCCB_I2C_FREQ       CONFIG_EXAMPLE_MIPI_CSI_CAM_MOTOR_SCCB_I2C_FREQ
#endif /* CONFIG_EXAMPLE_ENABLE_MIPI_CSI_CAM_MOTOR */
#endif /* CONFIG_EXAMPLE_ENABLE_MIPI_CSI_CAM_SENSOR */

/**
 * @brief DVP camera sensor common configuration
 */
#if CONFIG_EXAMPLE_ENABLE_DVP_CAM_SENSOR
#define EXAMPLE_ENABLE_DVP_CAM_SENSOR                   1
#if CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP
#define EXAMPLE_DVP_SCCB_I2C_PORT                       EXAMPLE_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */
#define EXAMPLE_DVP_SCCB_I2C_PORT                       CONFIG_EXAMPLE_DVP_SCCB_I2C_PORT
#endif /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */

#define EXAMPLE_DVP_SCCB_I2C_FREQ                       CONFIG_EXAMPLE_DVP_SCCB_I2C_FREQ


/**
 * @brief DVP clock frequency configuration
 */
#if (defined(EXAMPLE_DVP_XCLK_PIN) && EXAMPLE_DVP_XCLK_PIN >= 0)
#define EXAMPLE_DVP_XCLK_FREQ                           CONFIG_EXAMPLE_DVP_XCLK_FREQ
#else
#define EXAMPLE_DVP_XCLK_FREQ                           0
#endif /* EXAMPLE_DVP_XCLK_PIN >= 0 */
#endif /* CONFIG_EXAMPLE_ENABLE_DVP_CAM_SENSOR */

/**
 * @brief SPI camera sensor common configuration
 */
#if CONFIG_EXAMPLE_ENABLE_SPI_CAM_0_SENSOR
#if CONFIG_EXAMPLE_SPI_CAM_0_INTERFACE_SPI
#define EXAMPLE_SPI_CAM_0_INTERFACE                     ESP_CAM_CTLR_SPI_CAM_INTF_SPI
#elif CONFIG_EXAMPLE_SPI_CAM_0_INTERFACE_PARLIO
#define EXAMPLE_SPI_CAM_0_INTERFACE                     ESP_CAM_CTLR_SPI_CAM_INTF_PARLIO
#endif /* CONFIG_EXAMPLE_SPI_CAM_0_INTERFACE_SPI */

#if CONFIG_EXAMPLE_SPI_CAM_0_IO_MODE_2BIT
#define EXAMPLE_SPI_CAM_0_IO_MODE                       ESP_CAM_CTLR_SPI_CAM_IO_MODE_2BIT
#else /* CONFIG_EXAMPLE_SPI_CAM_0_IO_MODE_2BIT */
#define EXAMPLE_SPI_CAM_0_IO_MODE                       ESP_CAM_CTLR_SPI_CAM_IO_MODE_1BIT
#endif /* CONFIG_EXAMPLE_SPI_CAM_0_IO_MODE_2BIT */

#define EXAMPLE_ENABLE_SPI_CAM_SENSOR                   1
#define EXAMPLE_ENABLE_SPI_CAM_0_SENSOR                 1
#if CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP
#define EXAMPLE_SPI_CAM_0_SCCB_I2C_PORT                 EXAMPLE_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */
#define EXAMPLE_SPI_CAM_0_SCCB_I2C_PORT                 CONFIG_EXAMPLE_SPI_CAM_0_SCCB_I2C_PORT
#endif /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */
#define EXAMPLE_SPI_CAM_0_SCCB_I2C_FREQ                 CONFIG_EXAMPLE_SPI_CAM_0_SCCB_I2C_FREQ

/**
 * @brief SPI camera sensor SPI port configuration
 */
#define EXAMPLE_SPI_CAM_0_SPI_PORT                      CONFIG_EXAMPLE_SPI_CAM_0_SPI_PORT

/**
 * @brief SPI camera sensor clock resource configuration
 */
#if CONFIG_EXAMPLE_SPI_CAM_0_XCLK_USE_LEDC
#define EXAMPLE_SPI_CAM_0_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_LEDC
#elif CONFIG_EXAMPLE_SPI_CAM_0_XCLK_USE_CLOCK_ROUTER
#define EXAMPLE_SPI_CAM_0_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_ESP_CLOCK_ROUTER
#endif /* CONFIG_EXAMPLE_SPI_CAM_0_XCLK_USE_LEDC */

#if defined(EXAMPLE_SPI_CAM_0_XCLK_PIN) && EXAMPLE_SPI_CAM_0_XCLK_PIN >= 0
#define EXAMPLE_SPI_CAM_0_XCLK_FREQ                     CONFIG_EXAMPLE_SPI_CAM_0_XCLK_FREQ
#else
#define EXAMPLE_SPI_CAM_0_XCLK_FREQ                     0
#endif /* EXAMPLE_SPI_CAM_0_XCLK_PIN >= 0 */

#if CONFIG_EXAMPLE_SPI_CAM_0_XCLK_USE_LEDC
#define EXAMPLE_SPI_CAM_0_XCLK_TIMER                    CONFIG_EXAMPLE_SPI_CAM_0_XCLK_TIMER
#define EXAMPLE_SPI_CAM_0_XCLK_TIMER_CHANNEL            CONFIG_EXAMPLE_SPI_CAM_0_XCLK_TIMER_CHANNEL
#endif /* CONFIG_EXAMPLE_SPI_CAM_XCLK_USE_LEDC */

#if CONFIG_EXAMPLE_ENABLE_SPI_CAM_1_SENSOR
#define EXAMPLE_ENABLE_SPI_CAM_1_SENSOR                 1
#if CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP
#define EXAMPLE_SPI_CAM_1_SCCB_I2C_PORT                 EXAMPLE_SCCB_I2C_PORT_INIT_BY_APP
#else /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */
#define EXAMPLE_SPI_CAM_1_SCCB_I2C_PORT                 CONFIG_EXAMPLE_SPI_CAM_1_SCCB_I2C_PORT
#endif /* CONFIG_EXAMPLE_SCCB_I2C_INIT_BY_APP */
#define EXAMPLE_SPI_CAM_1_SCCB_I2C_FREQ                 CONFIG_EXAMPLE_SPI_CAM_1_SCCB_I2C_FREQ

#define EXAMPLE_SPI_CAM_1_SPI_PORT                      CONFIG_EXAMPLE_SPI_CAM_1_SPI_PORT

#if CONFIG_EXAMPLE_SPI_CAM_1_XCLK_USE_LEDC
#define EXAMPLE_SPI_CAM_1_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_LEDC
#elif CONFIG_EXAMPLE_SPI_CAM_1_XCLK_USE_CLOCK_ROUTER
#define EXAMPLE_SPI_CAM_1_XCLK_RESOURCE                 ESP_CAM_SENSOR_XCLK_ESP_CLOCK_ROUTER
#endif /* CONFIG_EXAMPLE_SPI_CAM_1_XCLK_USE_LEDC */

#if defined(EXAMPLE_SPI_CAM_1_XCLK_PIN) && EXAMPLE_SPI_CAM_1_XCLK_PIN >= 0
#define EXAMPLE_SPI_CAM_1_XCLK_FREQ                     CONFIG_EXAMPLE_SPI_CAM_1_XCLK_FREQ
#else
#define EXAMPLE_SPI_CAM_1_XCLK_FREQ                     0
#endif /* EXAMPLE_SPI_CAM_1_XCLK_PIN >= 0 */

#if CONFIG_EXAMPLE_SPI_CAM_1_XCLK_USE_LEDC
#define EXAMPLE_SPI_CAM_1_XCLK_TIMER                    CONFIG_EXAMPLE_SPI_CAM_1_XCLK_TIMER
#define EXAMPLE_SPI_CAM_1_XCLK_TIMER_CHANNEL            CONFIG_EXAMPLE_SPI_CAM_1_XCLK_TIMER_CHANNEL
#endif /* CONFIG_EXAMPLE_SPI_CAM_1_XCLK_USE_LEDC */
#endif /* CONFIG_EXAMPLE_ENABLE_SPI_CAM_1_SENSOR */
#endif /* CONFIG_EXAMPLE_ENABLE_SPI_CAM_0_SENSOR */

/**
 * @brief USB-UVC camera sensor common configuration
 */
#if CONFIG_EXAMPLE_ENABLE_USB_UVC_CAM_SENSOR
#define EXAMPLE_ENABLE_USB_UVC_CAM_SENSOR               1
#endif

/**
 * @brief Example camera device path configuration
 */
#if EXAMPLE_ENABLE_MIPI_CSI_CAM_SENSOR
#define EXAMPLE_CAM_DEV_PATH                            ESP_VIDEO_MIPI_CSI_DEVICE_NAME
#elif EXAMPLE_ENABLE_DVP_CAM_SENSOR
#define EXAMPLE_CAM_DEV_PATH                            ESP_VIDEO_DVP_DEVICE_NAME
#elif EXAMPLE_ENABLE_SPI_CAM_SENSOR
#define EXAMPLE_CAM_DEV_PATH                            ESP_VIDEO_SPI_DEVICE_NAME
#elif EXAMPLE_ENABLE_USB_UVC_CAM_SENSOR
#define EXAMPLE_CAM_DEV_PATH                            ESP_VIDEO_USB_UVC_DEVICE_NAME(0)
#else
#define EXAMPLE_CAM_DEV_PATH                            ESP_VIDEO_SPI_DEVICE_NAME
#endif /* CONFIG_EXAMPLE_ENABLE_MIPI_CSI_CAM_SENSOR */
