/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bridge_cmd.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bridge_cmd.pb-c.h"
void   bridge__bridge_command__init
                     (Bridge__BridgeCommand         *message)
{
  static const Bridge__BridgeCommand init_value = BRIDGE__BRIDGE_COMMAND__INIT;
  *message = init_value;
}
size_t bridge__bridge_command__get_packed_size
                     (const Bridge__BridgeCommand *message)
{
  assert(message->base.descriptor == &bridge__bridge_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bridge__bridge_command__pack
                     (const Bridge__BridgeCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bridge__bridge_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bridge__bridge_command__pack_to_buffer
                     (const Bridge__BridgeCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bridge__bridge_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bridge__BridgeCommand *
       bridge__bridge_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bridge__BridgeCommand *)
     protobuf_c_message_unpack (&bridge__bridge_command__descriptor,
                                allocator, len, data);
}
void   bridge__bridge_command__free_unpacked
                     (Bridge__BridgeCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bridge__bridge_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue bridge__msg_type__enum_values_by_number[3] =
{
  { "CMD", "BRIDGE__MSG_TYPE__CMD", 0 },
  { "RSP", "BRIDGE__MSG_TYPE__RSP", 1 },
  { "EVT", "BRIDGE__MSG_TYPE__EVT", 2 },
};
static const ProtobufCIntRange bridge__msg_type__value_ranges[] = {
  {0, 0}, {0, 3}
};
static const ProtobufCEnumValueIndex bridge__msg_type__enum_values_by_name[3] =
{
  { "CMD", 0 },
  { "EVT", 2 },
  { "RSP", 1 },
};
const ProtobufCEnumDescriptor bridge__msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "bridge.MsgType",
  "MsgType",
  "Bridge__MsgType",
  "bridge",
  3,
  bridge__msg_type__enum_values_by_number,
  3,
  bridge__msg_type__enum_values_by_name,
  1,
  bridge__msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor bridge__bridge_command__field_descriptors[8] =
{
  {
    "cmd_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, cmd_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, msg_type),
    &bridge__msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, req_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq_num",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, seq_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_final",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, is_final),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_size",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Bridge__BridgeCommand, total_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bridge__bridge_command__field_indices_by_name[] = {
  0,   /* field[0] = cmd_id */
  6,   /* field[6] = is_final */
  1,   /* field[1] = msg_type */
  4,   /* field[4] = payload */
  2,   /* field[2] = req_id */
  5,   /* field[5] = seq_num */
  3,   /* field[3] = status */
  7,   /* field[7] = total_size */
};
static const ProtobufCIntRange bridge__bridge_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor bridge__bridge_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bridge.BridgeCommand",
  "BridgeCommand",
  "Bridge__BridgeCommand",
  "bridge",
  sizeof(Bridge__BridgeCommand),
  8,
  bridge__bridge_command__field_descriptors,
  bridge__bridge_command__field_indices_by_name,
  1,  bridge__bridge_command__number_ranges,
  (ProtobufCMessageInit) bridge__bridge_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
