/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bridge_cmd.proto */

#ifndef PROTOBUF_C_bridge_5fcmd_2eproto__INCLUDED
#define PROTOBUF_C_bridge_5fcmd_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Bridge__BridgeCommand Bridge__BridgeCommand;


/* --- enums --- */

typedef enum _Bridge__MsgType {
  BRIDGE__MSG_TYPE__CMD = 0,
  BRIDGE__MSG_TYPE__RSP = 1,
  BRIDGE__MSG_TYPE__EVT = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BRIDGE__MSG_TYPE)
} Bridge__MsgType;

/* --- messages --- */

struct  Bridge__BridgeCommand
{
  ProtobufCMessage base;
  uint32_t cmd_id;
  Bridge__MsgType msg_type;
  uint32_t req_id;
  int32_t status;
  ProtobufCBinaryData payload;
  uint32_t seq_num;
  protobuf_c_boolean is_final;
  uint32_t total_size;
};
#define BRIDGE__BRIDGE_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bridge__bridge_command__descriptor) \
, 0, BRIDGE__MSG_TYPE__CMD, 0, 0, {0,NULL}, 0, 0, 0 }


/* Bridge__BridgeCommand methods */
void   bridge__bridge_command__init
                     (Bridge__BridgeCommand         *message);
size_t bridge__bridge_command__get_packed_size
                     (const Bridge__BridgeCommand   *message);
size_t bridge__bridge_command__pack
                     (const Bridge__BridgeCommand   *message,
                      uint8_t             *out);
size_t bridge__bridge_command__pack_to_buffer
                     (const Bridge__BridgeCommand   *message,
                      ProtobufCBuffer     *buffer);
Bridge__BridgeCommand *
       bridge__bridge_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bridge__bridge_command__free_unpacked
                     (Bridge__BridgeCommand *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Bridge__BridgeCommand_Closure)
                 (const Bridge__BridgeCommand *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    bridge__msg_type__descriptor;
extern const ProtobufCMessageDescriptor bridge__bridge_command__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_bridge_5fcmd_2eproto__INCLUDED */
